import pyautogui as pg
import time

pg.hotkey("win", "r")
pg.typewrite("https://youtu.be/lDeIjANwEOM?t=18\n")#la \n funciona como enter
pg.typewrite("k")
pg.hotkey("win", "r")
pg.typewrite("notepad\n")
time.sleep(3)
pg.typewrite("Ubugoe")
time.sleep(1)
pg.typewrite(" wo")
time.sleep(1)
pg.typewrite(" hibikasete\n")
time.sleep(3)
pg.typewrite("Amaneku")
time.sleep(1)
pg.typewrite(" yo")
time.sleep(1)
pg.typewrite(" ni")
time.sleep(1)
pg.typewrite(" shirase")
time.sleep(1)
pg.typewrite(" yo\n")
time.sleep(1.5)
pg.typewrite("Ten")
time.sleep(0.3)
pg.typewrite(" Kara")
time.sleep(0.8)
pg.typewrite(" no")
time.sleep(1.1)
pg.typewrite(" sazukarimono\n")
time.sleep(3.2)
pg.typewrite("Amata")
time.sleep(0.8)
pg.typewrite(" no")
time.sleep(0.5)
pg.typewrite(" inochi")
time.sleep(0.7)
pg.typewrite(" no")
time.sleep(1.2)
pg.typewrite(" naka\n")
time.sleep(2)
pg.typewrite("Mori")
time.sleep(0.8)
pg.typewrite(" wo")
time.sleep(0.6)
pg.typewrite(" moyasu")
time.sleep(1.3)
pg.typewrite(" akago")
time.sleep(1.2)
pg.typewrite(" wa\n")
time.sleep(1.7)
pg.typewrite("Dakare")
time.sleep(0.8)
pg.typewrite(" nemuru")
time.sleep(1.5)
pg.typewrite(" yoru")
time.sleep(0.8)
pg.typewrite(" mo")
time.sleep(0.8)
pg.typewrite(" naku\n")
time.sleep(1.2)
pg.typewrite("Chikara")
time.sleep(0.8)
pg.typewrite(" to")
time.sleep(1.5)
pg.typewrite(" hikikae")
time.sleep(0.8)
pg.typewrite(" ni")
time.sleep(0.8)
pg.typewrite(" shite\n")
time.sleep(1.6)
pg.typewrite("Ai")
time.sleep(0.8)
pg.typewrite(" ni")
time.sleep(0.9)
pg.typewrite(" furerarezu")
